# Generated by Django 5.2.14 on 2026-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0027_scanjob_is_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="coverage",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
