# Generated by Django 5.2.14 on 2026-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0028_scanjob_coverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="ruleset_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="scoring_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
