# Generated by Django 5.2.14 on 2026-10-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0029_scanjob_scoring_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="performance_report",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
