# Generated by Django 5.2.14 on 2026-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0030_scanjob_performance_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="fingerprint",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
